remote_theme: cotes2020/jekyll-theme-chirpy

theme_mode: dark
title: The Tech™
description: "A blog powered by Chirpy theme and Jekyll"
url: "https://drakefy.github.io"
baseurl: "/Peripheral-Buying-Guide"
theme: jekyll-theme-chirpy